services:
  resource_web:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/templates
      - ./certs/:/etc/nginx/certs/
    environment:
      - UPSTREAM=resource_backend
    ports:
      - 8010:443
    depends_on:
      - resource_backend

  resource_backend:
    build:
      context: resource
    stop_signal: SIGINT
    env_file: resource/.env
    command:
      [
        "uvicorn",
        "api.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8080",
        "--reload",
      ]
    volumes:
      - ./resource/api:/code/api
