services:
  authentication_web:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/templates
      - ./certs/:/etc/nginx/certs/
    environment:
      - UPSTREAM=authentication_backend
    ports:
      - 8000:443
      # - 443:443
    command: [nginx-debug, "-g", "daemon off;"]
    depends_on:
      - authentication_backend

  authentication_backend:
    build:
      context: authentication
    stop_signal: SIGINT
    env_file:
      - authentication/.env
    environment:
      - REDIS_HOST=redis
      - CALLBACK_URL=http://host.docker.internal:3000/callback
    command:
      [
        "uvicorn",
        "api.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8080",
        "--reload",
      ]
    volumes:
      - ./authentication/api:/code/api

  resource_web:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/templates
      - ./certs/:/etc/nginx/certs/
    environment:
      - UPSTREAM=resource_backend
    ports:
      - 8010:443
    depends_on:
      - resource_backend

  resource_backend:
    build:
      context: resource
    stop_signal: SIGINT
    environment:
      - ISSUER_URL=http://host.docker.internal:8020
    command:
      [
        "uvicorn",
        "api.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8080",
        "--reload",
      ]
    volumes:
      - ./resource/api:/code/api

  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
