services:
  authentication_web:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/templates
      - ./certs/:/etc/nginx/certs/
    environment:
      - UPSTREAM=authentication_backend
    ports:
      - 8000:443
      # - 443:443
    depends_on:
      - authentication_backend

  authentication_backend:
    build:
      context: authentication
    stop_signal: SIGINT
    environment:
      - FAPI_API=http://host.docker.internal:8020
      # - FAPI_API=https://perseus-demo-fapi.ib1.org
    command: ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    volumes:
      - ./authentication/api:/code/api

  resource_web:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/templates
      - ./certs/:/etc/nginx/certs/
    environment:
      - UPSTREAM=resource_backend
    ports:
      - 8010:443
    depends_on:
      - resource_backend

  resource_backend:
    build:
      context: resource
    stop_signal: SIGINT
    environment:
      - ISSUER_URL=http://host.docker.internal:8020
      # - FAPI_API=https://perseus-demo-fapi.ib1.org
    command: ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    volumes:
      - ./resource/api:/code/api
