services:
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs/:/etc/nginx/certs/
    environment:
      - FLASK_SERVER_ADDR=backend:8080
    # command: /bin/bash -c "envsubst '\$FLASK_SERVER_ADDR' < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && cat /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 8000:80
      - 443:443
    depends_on:
      - backend

  backend:
    build:
      context: backend
    stop_signal: SIGINT
    environment:
      - FAPI_API=http://host.docker.internal:8020
      # - FAPI_API=https://perseus-demo-fapi.ib1.org
    command: ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    volumes:
      - ./backend/api:/code/api
